Repository Lee4-M/DAT076, pull requests merged in 2025-03, with the labels that each got.

#82 Implement majority of frontend tests
  client/src/api/api.ts
  client/src/components/BudgetModal.test.tsx
  client/src/components/BudgetRowComponent.test.tsx
  client/src/components/BudgetTable.test.tsx
  client/src/components/ExpenseAccordion.test.tsx
  client/src/components/ExpenseAccordion.tsx
  client/src/components/ExpenseModal.test.tsx
  client/src/components/Sidebar.test.tsx
  client/src/routes/Login.test.tsx
  client/src/routes/LoginScreen.tsx
  client/src/routes/RegisterScreen.test.tsx
Labels: testing

#84 Documentation
  client/src/api/api.ts
  client/src/api/apiLogin.ts
  client/src/components/BudgetModal.test.tsx
  client/src/components/BudgetModal.tsx
  client/src/components/BudgetRowComponent.test.tsx
  client/src/components/BudgetRowComponent.tsx
  client/src/components/BudgetTable.tsx
  client/src/components/DraggableExpense.tsx
  client/src/components/ExpenseAccordion.test.tsx
  client/src/components/ExpenseAccordion.tsx
  client/src/components/ExpenseModal.tsx
  client/src/components/Sidebar.tsx
  client/src/routes/App.tsx
  server/package-lock.json
  server/src/db/expense.db.ts
  server/src/router/budget.ts
  server/src/router/budgetRowRouter.test.ts
  server/src/router/expense.ts
  server/src/router/expenseRouter.test.ts
  server/src/router/user.ts
  server/src/service/budget.ts
  server/src/service/budgetRowService.test.ts
  server/src/service/expense.ts
  server/src/service/expenseService.test.ts
  server/src/service/interface/IBudgetRowService.ts
  server/src/service/interface/IExpenseService.ts
  server/src/service/user.ts
Labels: documentation, refactoring

#85 Modified documentation and cleaned up codebase
  README.md
  client/README.md
  client/public/vite.svg
  client/src/api/api.ts
  client/src/assets/react.svg
  client/src/components/BudgetModal.test.tsx
  client/src/components/BudgetModal.tsx
  client/src/components/BudgetRowComponent.test.tsx
  client/src/components/BudgetRowComponent.tsx
  client/src/components/BudgetTable.test.tsx
  client/src/components/BudgetTable.tsx
  client/src/components/DraggableExpense.tsx
  client/src/components/ExpenseAccordion.test.tsx
  client/src/components/ExpenseModal.test.tsx
  client/src/components/ExpenseModal.tsx
  client/src/components/Sidebar.test.tsx
  client/src/components/Sidebar.tsx
  client/src/main.tsx
  client/src/routes/App.tsx
  client/src/routes/Login.test.tsx
  client/src/routes/LoginScreen.tsx
  client/src/routes/RegisterScreen.test.tsx
  client/src/routes/RegisterScreen.tsx
  project-report/DAT076_Project_Report.pdf
  server/src/db/budgetRow.db.ts
  server/src/db/expense.db.ts
  server/src/db/user.db.ts
  server/src/router/budget.ts
  server/src/router/budgetRowRouter.test.ts
  server/src/router/expense.ts
  server/src/router/expenseRouter.test.ts
  server/src/router/user.ts
  server/src/router/userRouter.test.ts
  server/src/service/budget.ts
  server/src/service/budgetRowService.test.ts
  server/src/service/expense.ts
  server/src/service/expenseService.test.ts
Labels: documentation, testing, refactoring
